plugins {
    id 'java'
}

repositories {
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.extendedclip.com/releases/' }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${rootProject.paper_version}"
    compileOnly 'me.clip:placeholderapi:2.11.7'
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

test { useJUnitPlatform() }

jar {
    archiveBaseName = 'RivalPlugins'
}
